version: 0.0.1
mqtt_topics:
  pump_1_flow_rate: "fuxa/md/fir_1"
  pump_1_temperature: "fuxa/md/tic_12"
  pump_2_flow_rate: "fuxa/md/fir_2"
  pump_2_temperature: "fuxa/md/tic_22"
  pump_1_sp: "fuxa/md/pump_11_sp"
  pump_2_sp: "fuxa/md/pump_21_sp"
  pump_1_manual: "fuxa/md/pump_11_manual"
  pump_2_manual: "fuxa/md/pump_21_manual"
  pump_1_manual_op: "fuxa/md/pump_11_manual_op"
  pump_2_manual_op: "fuxa/md/pump_21_manual_op"
  pump_1_op: "fuxa/md/pump_11_op"
  pump_2_op: "fuxa/md/pump_21_op"
  valve_heating_op: "fuxa/md/valve_31_op"
control_params:
  pump_1_pi_controller:
    default:
      u: 20.0
      sp: 3.0
    control:
      kp: 6.56
      ti: 28.19
    time_steps:
      tr: 5
      dt: 2
    saturation:
      top_limit: 50
      bottom_limit: 0
    anti_windup:
      gain: 0.1883
    hysteresis:
      top_offset: 1
      bottom_offset: 1
  pump_2_pi_controller:
    default:
      u: 20.0
      sp: 3.0
    control:
      kp: 7.60
      ti: 51.14
    time_steps:
      tr: 6
      dt: 2
    saturation:
      top_limit: 50
      bottom_limit: 0
    anti_windup:
      gain: 0.1398
    hysteresis:
      top_offset: 1
      bottom_offset: 1
